//go:build goexperiment.jsonv2

package emitter

import (
	"encoding/json/v2"
	"testing"
)

// TestStubOutput validates the exact JSON structure generated by EmitStub
func TestStubOutput(t *testing.T) {
	emitter := NewJSONEmitter()

	stub, err := emitter.EmitStub()
	if err != nil {
		t.Fatalf("EmitStub() error = %v", err)
	}

	data, err := emitter.MarshalDeterministic(stub)
	if err != nil {
		t.Fatalf("MarshalDeterministic() error = %v", err)
	}

	// Expected stub JSON structure
	expected := map[string]any{
		"meta": map[string]any{
			"partial": false,
			"stats": map[string]any{
				"filesParsed": float64(0),
				"skipped":     float64(0),
				"durationMs":  float64(0),
			},
		},
		"controllers": []any{},
		"models":      []any{},
		"polymorphic": []any{},
		"broadcast":   []any{},
	}

	var actual map[string]any
	if err := json.Unmarshal(data, &actual); err != nil {
		t.Fatalf("failed to unmarshal actual JSON: %v", err)
	}

	// Compare structure
	if !deepEqual(t, expected, actual) {
		t.Errorf("stub structure mismatch")
		t.Logf("Expected: %v", expected)
		t.Logf("Actual: %v", actual)
		t.Logf("JSON: %s", string(data))
	}

	// Verify the JSON is compact (no pretty printing)
	if len(data) == 0 {
		t.Error("JSON output is empty")
	}

	t.Logf("Generated stub JSON (%d bytes): %s", len(data), string(data))
}

// TestComplexDeltaDeterministicValidation ensures complex deltas produce valid, deterministic JSON
func TestComplexDeltaDeterministicValidation(t *testing.T) {
	emitter := NewJSONEmitter()

	// Create a comprehensive delta to test all schema elements
	delta := &Delta{
		Meta: MetaInfo{
			Partial: true, // Set partial=true to test this case
			Stats: MetaStats{
				FilesParsed: 42,
				Skipped:     7,
				DurationMs:  2500,
			},
		},
		Controllers: []Controller{
			{
				FQCN:   "App\\Http\\Controllers\\UserController",
				Method: "store",
				HTTP: &HTTPInfo{
					Status:   &[]int{201}[0],
					Explicit: &[]bool{true}[0],
				},
				Request: &RequestInfo{
					ContentTypes: []string{"application/json", "multipart/form-data"},
					Body:         NewOrderedObjectFromMap(map[string]any{"name": map[string]any{}, "email": map[string]any{}}),
					Query:        NewOrderedObjectFromMap(map[string]any{"include": map[string]any{}}),
					Files:        NewOrderedObjectFromMap(map[string]any{"avatar": map[string]any{}}),
				},
				Resources: []Resource{
					{Class: "UserResource", Collection: false},
				},
				ScopesUsed: []ScopeUsed{
					{On: "User", Name: "active", Args: []string{"true"}},
					{On: "User", Name: "verified"},
				},
			},
		},
		Models: []Model{
			{
				FQCN: "App\\Models\\User",
				WithPivot: []PivotInfo{
					{
						Relation:   "roles",
						Columns:    []string{"assigned_at", "level"},
						Alias:      &[]string{"user_role"}[0],
						Timestamps: &[]bool{true}[0],
					},
				},
				Attributes: []Attribute{
					{Name: "full_name", Via: "Attribute::make"},
					{Name: "display_name", Via: "Attribute::make"},
				},
			},
		},
		Polymorphic: []Polymorphic{
			{
				Parent: "App\\Models\\Comment",
				Morph: MorphInfo{
					Key:        "commentable",
					TypeColumn: "commentable_type",
					IdColumn:   "commentable_id",
				},
				Discriminator: Discriminator{
					PropertyName: "type",
					Mapping: map[string]string{
						"post":    "App\\Models\\Post",
						"product": "App\\Models\\Product",
						"user":    "App\\Models\\User",
					},
				},
				DepthTruncated: &[]bool{false}[0],
			},
		},
		Broadcast: []Broadcast{
			{
				File:           &[]string{"routes/channels.php"}[0],
				Channel:        "user.{id}.notifications",
				Params:         []string{"id"},
				Visibility:     "private",
				PayloadLiteral: &[]bool{false}[0],
			},
			{
				Channel:    "public.announcements",
				Params:     []string{},
				Visibility: "public",
			},
		},
	}

	// Marshal multiple times and verify deterministic output
	results := make([][]byte, 3)
	for i := 0; i < 3; i++ {
		data, err := emitter.MarshalDeterministic(delta)
		if err != nil {
			t.Fatalf("iteration %d: MarshalDeterministic() error = %v", i, err)
		}
		results[i] = data
	}

	// All results should be identical
	for i := 1; i < len(results); i++ {
		if string(results[0]) != string(results[i]) {
			t.Errorf("iteration %d produced different result than iteration 0", i)
			t.Logf("First:  %s", string(results[0]))
			t.Logf("Second: %s", string(results[i]))
			break
		}
	}

	// Validate structure
	var result map[string]any
	if err := json.Unmarshal(results[0], &result); err != nil {
		t.Fatalf("failed to unmarshal JSON: %v", err)
	}

	// Check meta.partial is true as expected
	if meta, ok := result["meta"].(map[string]any); ok {
		if partial, ok := meta["partial"].(bool); !ok || !partial {
			t.Error("expected meta.partial to be true")
		}
	}

	// Verify sorting - controllers should be sorted by FQCN
	if controllers, ok := result["controllers"].([]any); ok && len(controllers) > 0 {
		// In this case we only have one controller, but verify structure
		controller := controllers[0].(map[string]any)
		if controller["fqcn"] != "App\\Http\\Controllers\\UserController" {
			t.Errorf("unexpected controller FQCN: %v", controller["fqcn"])
		}
	}

	// Verify broadcast sorting - should be sorted by channel
	if broadcasts, ok := result["broadcast"].([]any); ok && len(broadcasts) >= 2 {
		first := broadcasts[0].(map[string]any)
		second := broadcasts[1].(map[string]any)

		firstChannel := first["channel"].(string)
		secondChannel := second["channel"].(string)

		if firstChannel > secondChannel {
			t.Errorf("broadcasts not sorted by channel: %s > %s", firstChannel, secondChannel)
		}
	}

	t.Logf("Complex delta JSON (%d bytes): %s", len(results[0]), string(results[0]))
}

// deepEqual compares two interface{} values for deep equality
func deepEqual(t *testing.T, expected, actual any) bool {
	expectedJSON, err := json.Marshal(expected, json.Deterministic(true))
	if err != nil {
		t.Errorf("failed to marshal expected: %v", err)
		return false
	}

	actualJSON, err := json.Marshal(actual, json.Deterministic(true))
	if err != nil {
		t.Errorf("failed to marshal actual: %v", err)
		return false
	}

	return string(expectedJSON) == string(actualJSON)
}
